name: C Compiler Error-Check

on:
  push:
    branches: [ "main" ]
    paths: [ "disassembler/**", "emulator/**" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "disassembler/**", "emulator/**" ]

defaults:
  run:
    shell: msys2 {0}

jobs:
  build:

    runs-on: windows-latest

    steps:

    - uses: msys2/setup-msys2@v2
      with:
        release: false
        msystem: MSYS
        update: true
        install: >-
          base-devel
          mingw-w64-x86_64-SDL2

    - uses: actions/checkout@v3

    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          disassembler:
            - "disassembler/**"
          emulator:
            - "emulator/**"
          machine:
            - "machine/**"
          main:
            - "main.cpp"

    - name: make disassembler
      if: ${{ steps.changes.outputs.disassembler == 'true' }}
      run: |
        cd disassembler
        make disassembler

    - name: make emulator
      if: ${{ steps.changes.outputs.emulator == 'true' }}
      run: |
        cd emulator
        make emulator

    - name: make emulator_debug
      if: ${{ steps.changes.outputs.emulator == 'true' || steps.changes.outputs.disassembler == 'true' }}
      run: |
        cd emulator
        make emulator_debug

    - name: make main
      if: ${{ steps.changes.outputs.emulator == 'true' || steps.changes.outputs.machine == 'true' || steps.changes.outputs.main == 'true' }}
      run: make main
