name: C Compiler Error-Check

on:
  push:
    branches: [ "main" ]
    paths: [ "disassembler/**", "emulator/**" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "disassembler/**", "emulator/**" ]

defaults:
  run:
    shell: msys2 {0}

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MSYS
        update: true
        install: >-
          base-devel
          mingw-w64-x86_64-SDL2
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          disassembler:
            - "disassembler/**"
          emulator:
            - "emulator/**"
          machine:
            - "machine/**"
          main:
            - main.cpp
    - name: setup environment
      run: echo "D:/a/_temp/msys64/mingw64/bin" >> $GITHUB_PATH

    - name: make disassembler
      if: ${{ steps.changes.outputs.disassembler == 'true' }}
      run: make disassembler
      working-directory: disassembler

    - name: make emulator
      if: ${{ steps.changes.outputs.emulator == 'true' }}
      run: make emulator
      working-directory: emulator

    - name: make emulator_debug
      if: ${{ steps.changes.outputs.emulator == 'true' || steps.changes.outputs.disassembler == 'true' }}
      run: make emulator_debug
      working-directory: emulator

    - name: make main
      if: ${{ steps.changes.outputs.emulator == 'true' || steps.changes.outputs.machine == 'true' || steps.changes.outputs.main == 'true' }}
      run: make main
      working-directory: ${GITHUB_WORKSPACE}
